import type { CanonicalItem } from "../matchParsedLineToCanonical";
import type { StoreProduct } from "../selectBestStore";
import { toCatalogSchemaRecord } from "../catalog/catalogSchema";

// Synthetic (in-memory) catalog used until a real DB/API integration exists.
// IDs are deterministic so debugging is repeatable.

const IDS = {
  milk: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0001",
  eggs: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0002",
  banana: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0003",
  chicken: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0004",
  rice: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0005",
  walmart: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb001",
  loblaws: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb002",
} as const;

export function getSyntheticCanonicalItems(): CanonicalItem[] {
  return [
    {
      id: IDS.milk,
      slug: "milk",
      display_name: "Milk",
      category: "dairy",
      default_attributes_json: { fat: "2%", lactoseFree: false, organic: false },
      attribute_schema_json: {
        fat: ["skim", "1%", "2%", "whole"],
        lactoseFree: [true, false],
        organic: [true, false],
      },
      aliases_json: ["milk", "dairy milk", "cow milk"],
    },
    {
      id: IDS.eggs,
      slug: "eggs",
      display_name: "Eggs",
      category: "protein",
      default_attributes_json: { size: "large", eggCount: 12, organic: false, cageFree: false },
      attribute_schema_json: {
        size: ["small", "large", "jumbo"],
        eggCount: [6, 12, 18],
        organic: [true, false],
        cageFree: [true, false],
      },
      aliases_json: ["eggs", "egg"],
    },
    {
      id: IDS.banana,
      slug: "banana",
      display_name: "Banana",
      category: "produce",
      default_attributes_json: { ripeness: "yellow", organic: false },
      attribute_schema_json: {
        ripeness: ["green", "yellow", "ripe"],
        organic: [true, false],
      },
      aliases_json: ["banana", "bananas"],
    },
    {
      id: IDS.chicken,
      slug: "chicken",
      display_name: "Chicken",
      category: "meat",
      default_attributes_json: { cut: "breast", organic: false, boneless: true, skinless: true },
      attribute_schema_json: {
        cut: ["breast", "thigh", "ground"],
        organic: [true, false],
        boneless: [true, false],
        skinless: [true, false],
      },
      aliases_json: ["chicken"],
    },
    {
      id: IDS.rice,
      slug: "rice",
      display_name: "Rice",
      category: "pantry",
      default_attributes_json: { type: "white", organic: false },
      attribute_schema_json: {
        type: ["white", "brown", "basmati", "jasmine"],
        organic: [true, false],
      },
      aliases_json: ["rice", "white rice", "brown rice"],
    },
  ];
}

export function getSyntheticCatalogSchemaRecords() {
  return getSyntheticCanonicalItems().map((item) => toCatalogSchemaRecord(item));
}

export function getSyntheticStoreProducts(): StoreProduct[] {
  // Attributes intentionally align with what the rule-based parser produces as defaults.
  return [
    // ----------------- MILK -----------------
    {
      store_id: IDS.walmart,
      canonical_item_id: IDS.milk,
      price_cents: 298,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 25,
      in_stock: true,
      attributes_json: { fat: "2%", lactoseFree: false, organic: false },
      metadata_json: { etaMin: 25, inStock: true, brand: "Great Value", sizeText: "1L" },
    },
    {
      store_id: IDS.walmart,
      canonical_item_id: IDS.milk,
      price_cents: 349,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 25,
      in_stock: true,
      attributes_json: { fat: "whole", lactoseFree: false, organic: false },
      metadata_json: { etaMin: 25, inStock: true, brand: "Great Value", sizeText: "1L" },
    },
    {
      store_id: IDS.loblaws,
      canonical_item_id: IDS.milk,
      price_cents: 319,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 35,
      in_stock: true,
      attributes_json: { fat: "2%", lactoseFree: false, organic: false },
      metadata_json: { etaMin: 35, inStock: true, brand: "President's Choice", sizeText: "1L" },
    },
    {
      store_id: IDS.loblaws,
      canonical_item_id: IDS.milk,
      price_cents: 369,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 35,
      in_stock: true,
      attributes_json: { fat: "whole", lactoseFree: false, organic: false },
      metadata_json: { etaMin: 35, inStock: true, brand: "President's Choice", sizeText: "1L" },
    },

    // ----------------- EGGS -----------------
    {
      store_id: IDS.walmart,
      canonical_item_id: IDS.eggs,
      price_cents: 488,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 25,
      in_stock: true,
      attributes_json: { size: "large", eggCount: 12, organic: false, cageFree: false },
      metadata_json: { etaMin: 25, inStock: true, brand: "Great Value", sizeText: "12 large" },
    },
    {
      store_id: IDS.walmart,
      canonical_item_id: IDS.eggs,
      price_cents: 399,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 25,
      in_stock: true,
      attributes_json: { size: "large", eggCount: 6, organic: true, cageFree: false },
      metadata_json: { etaMin: 25, inStock: true, brand: "Great Value Organic", sizeText: "6" },
    },
    {
      store_id: IDS.loblaws,
      canonical_item_id: IDS.eggs,
      price_cents: 515,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 35,
      in_stock: true,
      attributes_json: { size: "large", eggCount: 12, organic: false, cageFree: false },
      metadata_json: { etaMin: 35, inStock: true, brand: "No Name", sizeText: "12 large" },
    },
    {
      store_id: IDS.loblaws,
      canonical_item_id: IDS.eggs,
      price_cents: 429,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 35,
      in_stock: true,
      attributes_json: { size: "large", eggCount: 6, organic: true, cageFree: false },
      metadata_json: { etaMin: 35, inStock: true, brand: "President's Choice Organic", sizeText: "6" },
    },

    // ----------------- BANANA -----------------
    {
      store_id: IDS.walmart,
      canonical_item_id: IDS.banana,
      price_cents: 258,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 25,
      in_stock: true,
      attributes_json: { ripeness: "yellow", organic: false },
      metadata_json: { etaMin: 25, inStock: true, brand: "In-store", sizeText: "2lb" },
    },
    {
      store_id: IDS.walmart,
      canonical_item_id: IDS.banana,
      price_cents: 549,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 25,
      in_stock: true,
      attributes_json: { ripeness: "ripe", organic: true },
      metadata_json: { etaMin: 25, inStock: true, brand: "Greenhouse Organic", sizeText: "3lb" },
    },
    {
      store_id: IDS.loblaws,
      canonical_item_id: IDS.banana,
      price_cents: 279,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 35,
      in_stock: true,
      attributes_json: { ripeness: "yellow", organic: false },
      metadata_json: { etaMin: 35, inStock: true, brand: "In-store", sizeText: "2lb" },
    },
    {
      store_id: IDS.loblaws,
      canonical_item_id: IDS.banana,
      price_cents: 599,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 35,
      in_stock: true,
      attributes_json: { ripeness: "ripe", organic: true },
      metadata_json: { etaMin: 35, inStock: true, brand: "In-store", sizeText: "3lb" },
    },

    // ----------------- CHICKEN -----------------
    {
      store_id: IDS.walmart,
      canonical_item_id: IDS.chicken,
      price_cents: 898,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 25,
      in_stock: true,
      attributes_json: { cut: "breast", organic: false, boneless: true, skinless: true },
      metadata_json: { etaMin: 25, inStock: true, brand: "Great Value", sizeText: "2lb" },
    },
    {
      store_id: IDS.walmart,
      canonical_item_id: IDS.chicken,
      price_cents: 1299,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 25,
      in_stock: true,
      attributes_json: { cut: "thigh", organic: true, boneless: true, skinless: true },
      metadata_json: { etaMin: 25, inStock: true, brand: "Greenhouse Organic", sizeText: "2lb" },
    },
    {
      store_id: IDS.loblaws,
      canonical_item_id: IDS.chicken,
      price_cents: 949,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 35,
      in_stock: true,
      attributes_json: { cut: "breast", organic: false, boneless: true, skinless: true },
      metadata_json: { etaMin: 35, inStock: true, brand: "No Name", sizeText: "2lb" },
    },
    {
      store_id: IDS.loblaws,
      canonical_item_id: IDS.chicken,
      price_cents: 1349,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 35,
      in_stock: true,
      attributes_json: { cut: "thigh", organic: true, boneless: true, skinless: true },
      metadata_json: { etaMin: 35, inStock: true, brand: "President's Choice Organic", sizeText: "2lb" },
    },

    // ----------------- RICE -----------------
    {
      store_id: IDS.walmart,
      canonical_item_id: IDS.rice,
      price_cents: 649,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 25,
      in_stock: true,
      attributes_json: { type: "white", organic: false },
      metadata_json: { etaMin: 25, inStock: true, brand: "Great Value", sizeText: "5lb" },
    },
    {
      store_id: IDS.walmart,
      canonical_item_id: IDS.rice,
      price_cents: 899,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 25,
      in_stock: true,
      attributes_json: { type: "brown", organic: true },
      metadata_json: { etaMin: 25, inStock: true, brand: "Nature's Harvest Organic", sizeText: "4lb" },
    },
    {
      store_id: IDS.loblaws,
      canonical_item_id: IDS.rice,
      price_cents: 699,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 35,
      in_stock: true,
      attributes_json: { type: "white", organic: false },
      metadata_json: { etaMin: 35, inStock: true, brand: "No Name", sizeText: "5lb" },
    },
    {
      store_id: IDS.loblaws,
      canonical_item_id: IDS.rice,
      price_cents: 949,
      currency: "CAD",
      availability_status: "in_stock",
      eta_min: 35,
      in_stock: true,
      attributes_json: { type: "brown", organic: true },
      metadata_json: { etaMin: 35, inStock: true, brand: "President's Choice Organic", sizeText: "4lb" },
    },
  ];
}

